OFS-13: Added models and services shell
openimis/openimis-be-policyholder_py pull request #1
Opened 2020-10-02 09:32 UTC by dborowiecki

Work in progress
TICKET: [OFS-13](https://openimis.atlassian.net/browse/OFS-13)

2020-10-02 10:19 UTC, dragos-dobre requested changes

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    legal_form = models.IntegerField(db_column='LegalForm')
From spec, this should be a FK to dictionary.

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    activity_code = models.IntegerField(db_column='ActivityCode')
From spec, this should be a FK to dictionary.

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    date_update = fields.DateTimeField(db_column="DateUpdate")
Change to data_updated. Change to other models too.

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    user_update = models.ForeignKey(core_models.InteractiveUser, db_column="UserUpdateUUID",related_name="%(class)s_UpdateUUID",
Change to user_updated.Change to other models too.

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    user_create = models.ForeignKey(core_models.InteractiveUser, db_column="UserCreateUUID",related_name="%(class)s_CreateUUID",
Change to user_created.  Change to other models too.

2020-10-02 10:19 UTC, dragos-dobre commented on policyholder/models.py
> +    # user = models.ForeignKey(ContributionPlanBundle, db_column='ContribuiotnPlanBundleId',
user is a link to tblUsers. It will be updated on the wiki page.

2020-10-02 12:53 UTC, delcroip commented on policyholder/models.py
> +    legal_form = models.IntegerField(db_column='LegalForm')
I have to update the spec as per discussion with Xavier --> this will be in the config

2020-10-02 12:53 UTC, delcroip commented on policyholder/models.py
> +    activity_code = models.IntegerField(db_column='ActivityCode')
I have to update the spec as per discussion with Xavier --> this will be in the config

2020-10-02 15:06 UTC, delcroip commented on policyholder/models.py
> +    date_update = fields.DateTimeField(db_column="DateUpdate")
Data ot date_updated ?

2020-10-05 07:19 UTC, dborowiecki commented on policyholder/models.py
> +    date_update = fields.DateTimeField(db_column="DateUpdate")
Changed to date_updated

2020-10-05 07:20 UTC, dborowiecki commented on policyholder/models.py
> +    user_update = models.ForeignKey(core_models.InteractiveUser, db_column="UserUpdateUUID",related_name="%(class)s_UpdateUUID",
Done

2020-10-05 07:20 UTC, dborowiecki commented on policyholder/models.py
> +    user_create = models.ForeignKey(core_models.InteractiveUser, db_column="UserCreateUUID",related_name="%(class)s_CreateUUID",
Done

2020-10-05 07:24 UTC, dborowiecki commented on policyholder/models.py
> +    # user = models.ForeignKey(ContributionPlanBundle, db_column='ContribuiotnPlanBundleId',
Changed

2020-10-07 10:21 UTC, dborowiecki commented on policyholder/models.py
> +    legal_form = models.IntegerField(db_column='LegalForm')
@delcroip as the specification has been changed, can you confirm that the integer is the right type for this attribute?

2020-10-09 09:37 UTC, delcroip requested changes

2020-10-09 09:37 UTC, delcroip commented on policyholder/services.py
create, update delete missing

2020-10-09 10:03 UTC, dborowiecki commented on policyholder/services.py
@delcroip Missing methods added

2020-10-30 18:58 UTC, dborowiecki commented
@delcroip I've added requested changes, some improvement to models and test helpers. Changes for this branch are depending on content from [this contribution plan bundle PR](https://github.com/openimis/openimis-be-contribution_plan_py/pull/2) so please first take a look at that PR.

2020-11-04 09:32 UTC, dragos-dobre approved these changes

2020-11-04 19:54 UTC, delcroip approved these changes

2020-11-04 19:54 UTC, merged