OFS-89: Updated model for PolicyHolder and some basic changes in graphQL queries and mutations in that module
openimis/openimis-be-policyholder_py pull request #2
Opened 2020-11-25 14:48 UTC by sniedzielski

In that pull request I want to merge some changes in PolicyHolder backend connected with updating models. There are some changes in test files and in graphQL mutations and queries so as to check whether newly updated model works correctly. In another pull request I will merge deletion and replace mutations. But not now. 

Moreover I had to change the type of models from JSON to TextField. There are some problems with JSON fields I mean the filters don't work correctly because django (django==3.0.3 - actual version from requirements.txt in backend) doesn't support such JSON filters on SQL Server. 

I have such error on filtering by such JSON field. 
"Transforms on JSONFields are only supported on PostgreSQL and MySQL at the moment."

And I'm sending interesting link https://docs.djangoproject.com/en/3.1/releases/3.1/
"JSONField for all supported database backends" - in that section there is interesting point about JSON fields. But unfortunately there is for django 3.1 and we have 3.0.3.

2020-11-25 14:58 UTC, sniedzielski commented
And furthermore there is another pull request connected with this ticket on openimis backend core https://github.com/openimis/openimis-be-core_py/pull/24. I had to make some changes in core because of writing new filter for filtering objects by field "is_deleted" and fixing some minor bugs in core module.

2020-11-25 15:43 UTC, delcroip requested changes

2020-11-25 15:43 UTC, delcroip commented on policyholder/models.py
> +    address = models.TextField(db_column='Address', blank=True, null=True)
in the core mode this is used for JSON 
```
FallbackJSONField(
        db_column='JsonExt', blank=True, null=True)

```

2020-11-25 15:43 UTC, delcroip commented on policyholder/models.py
> +    bank_account = models.TextField(db_column="bankAccount", blank=True, null=True)
in the core mode this is used for JSON

FallbackJSONField(
        db_column='JsonExt', blank=True, null=True)

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/base_mutation.py
> +from functools import lru_cache
I believed the goal was to migrate this in the core so it will be available in other modules

2020-11-25 15:43 UTC, delcroip commented on policyholder/models.py
>      locations_uuid = models.ManyToManyField(Location, verbose_name="LocationsUUID", blank=True)
I like the idea of manytomany but I believe it is not supported by django-simple-history, Either we simply store the data in json , or create a relationship model and remove it from PH, or we support only one location

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/input_types.py
> +    location_ids = graphene.List(graphene.Int)
see comment above

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
this is likely to be an uuid

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
this is likely to be an uuid

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
this is likely to be an uuid

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
this is likely to be an uuid

2020-11-25 15:43 UTC, delcroip commented on policyholder/qgl/gql_types.py
> +            "user": ["exact"],
I guess you are not using the **prefix_filtered for the user because it doesn't exist ?

2020-11-25 19:18 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/base_mutation.py
> +from functools import lru_cache
Yes, it will be migrated to the core. But currently I have to delay this task because Rafal @rstencel is waiting for me to deliver backend of PolicyHolder. After this I will migrate that to the core module and another modules like ContributionPlanBundle etc can use this.

2020-11-25 19:20 UTC, sniedzielski commented on policyholder/models.py
>      locations_uuid = models.ManyToManyField(Location, verbose_name="LocationsUUID", blank=True)
Ok, I can change it and choose one of your propositions. The idea with JSON is ok. Supporting one location is also a quite good idea but seems to have some disadvantages.

2020-11-25 19:20 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    location_ids = graphene.List(graphene.Int)
ok

2020-11-25 19:20 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
ok

2020-11-25 19:20 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
ok

2020-11-25 19:21 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    location_ids = graphene.List(graphene.Int)
ok

2020-11-25 19:21 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
ok

2020-11-25 19:21 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
ok

2020-11-25 19:21 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
ok

2020-11-25 19:21 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
ok

2020-11-26 09:24 UTC, sniedzielski commented on policyholder/models.py
>      locations_uuid = models.ManyToManyField(Location, verbose_name="LocationsUUID", blank=True)
Ok, I also talked about it with @rstencel and I've changed this field as a foreign key.

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/models.py
>      locations_uuid = models.ManyToManyField(Location, verbose_name="LocationsUUID", blank=True)
Ok, I've commited changes of this field "locations_uuid" and I've added filter for it.

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    location_ids = graphene.List(graphene.Int)
fixed

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
fixed

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
fixed

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    contribution_plan_bundle_id = graphene.Int(requried=False)
fixed

2020-11-26 09:49 UTC, sniedzielski commented on policyholder/qgl/gql_mutations/input_types.py
> +    policy_holder_id = graphene.Int(required=False)
fixed

2020-11-26 09:51 UTC, sniedzielski commented on policyholder/qgl/gql_types.py
> +            "user": ["exact"],
Yes. And according to @dborowiecki and me it isn't necessary. The "exact" should be enough in that case.

2020-11-26 13:14 UTC, delcroip approved these changes

2020-11-26 13:14 UTC, merged